### PR TITLE
Use burningwave lib to export javac packages from module

### PR DESCRIPTION
**Pull request by klaraward**
Attempt to solve the problem of running the plugin with Java 17, but without forking to add JVM args.

Could try hiding this behind a setting as a start, in case it causes problems....

### CODE REVIEW

**Comment by danielnorberg** [comment]
Note that Burningwave does not seem to support aarch64, so this would now work for folks with arm linux laptops and m1 macbooks etc.

**Comment by klaraward** [comment]
The burningwave lib feels a bit like overkill for this, and forking the plugin is more flexible, closing this and going with #140

**Comment by klaraward** [comment]
At least this little part worked fine with an aarch64 JDK.

**Comment by danielnorberg** [comment]
Trying to get some more clues on how this works and when/if it might break https://github.com/burningwave/jvm-driver/issues/2

**Comment by danielnorberg** [comment]
If I change `exportCompilerPackages` default to `true` then integration tests pass locally with corretto 17 after rebasing on https://github.com/spotify/fmt-maven-plugin/pull/145.

**Comment by klaraward** [comment]
Went with forking. #140

**Pull request closed without merging**
