### PR TITLE
Add failOnError parameter

### PR DESCRIPTION
**Pull request by klaraward**
Solves #59 

Per discussions below naming parameter `failOnError`

### CODE REVIEW

**Comment by Stephan202** [comment]
> Is there a standard for naming this parameter? Some call it `failOnWarning` (which would be default true in our case)

It seems plugins use a wide range of variants; see [this section](https://github.com/PicnicSupermarket/oss-parent/blob/0a262a2ce4d63561435ac4d9ac35ee9ec38b13f6/pom.xml#L1063-L1145) for a number of examples.

(_Thanks_ for picking this up; it'll allow us to drop [this special treatment](https://github.com/PicnicSupermarket/oss-parent/blob/0a262a2ce4d63561435ac4d9ac35ee9ec38b13f6/pom.xml#L1146-L1170) of `fmt-maven-plugin` :+1:.)

**Comment by danielnorberg** [comment]
Indeed there does not seem to be a strong standard around naming, but some variant of `failOnXYZ` seem common. E.g. `failOnError`, `failsOnError`, `failOnViolation`, `failOnWarning`, etc.

**Comment by klaraward** [comment]
Thanks @Stephan202 and @danielnorberg for the examples 👍 
I think some `failOnXYZ` would be my preference. `failOnNonComply` is a bit bulky :)
Will change PR to use `failOnWarning` for now.

**Comment by danielnorberg** [comment]
Do we consider the formatting violations to be "warnings" or "errors"? 

I believe warnings usually do not by default fail builds whereas errors do.

If we want to keep the behavior of failing the build on formatting violations by default then I'd consider them to be "errors" and call this parameter `failOnError`.

**Comment by klaraward** [comment]
I guess since the whole job of the check goal is to find the errors, and the output is not warnings in the process of doing something else, in contrast to the compiler plugin that compiles AND shows any warnings, that failOnError, or maybe the failOnViolation, makes a lot of sense.
failOnError is a bit easier to read and write, so lets go with tag.

**Comment by danielnorberg** [comment]
sgtm

**Review by danielnorberg — APPROVED** [review]

**Review by herder — APPROVED** [review]

**Pull request merged**
